apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name  }}-{{ .Release.name }}
  labels:
    app: {{ .Chart.Name  }}-{{ .Release.name }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Chart.Name  }}-{{ .Release.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name  }}-{{ .Release.name }}
    spec:
      containers:
      - name: {{ .Chart.Name  }}
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
