apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  completions: 5 # должно успешно выполниться не менее 5 раз, чтоб задача считалась выполенной, по умолчанию стоит 1
  parallelism: 2 # количество подов, запускаемых параллельно, по умолчанию стоит 1
  ttlSecondsAfterFinished: 6000 # столько секунд описание джобы будет висеть в информации о кластере, потом эта информация будет удалена
  # и будет непонятно что стало с джобой, была она успешна или нет

  backoffLimit: 2 # если после двух попыток не будет выхода 0, то третьей попытки не будет
  activeDeadlineSeconds: 1 # ждём после запуска 60 секунд и если не завершилась, то кубер считает что зависло
  template:
    spec:
      containers:
      - name: hello
        image: quay.io/prometheus/busybox
        args:
        - /bin/sh
        - -c
        - date; echo Hello from the Kubernetes cluster; sleep 100 # по коду выхода этой команды кубер понимает, зафейлилась задача или была успешна
      restartPolicy: Never # политика перезапуска контейнера внутри пода(не самого пода) - сейчас контейнер внутри пода не перезапускаем, а запускаем новый под
      # Always - технически теперь нельзя ставить
      # OnFailor ещё бывает
