---
# file: practice/1.kube-basics-lecture/4.resources-and-probes/deployment-with-stuff.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: quay.io/testing-farm/nginx:1.12
        name: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3 # ждем пока 3 раза зафейлится, пока принимать решение что нода фейлится
          httpGet: # httpGet это http проба, а может быть exec и тогда здесь может быть команда, также может быть проверка сокета
            path: / # 200 - 399 коды ответа окей, а 400 и выше - фейлится
            port: 80
          periodSeconds: 10 # время между проверками
          successThreshold: 1 # какое количество сакцессов удостоверит, что контейнер работает
          timeoutSeconds: 1 # таймаут проверки
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10 # ранняя версия стартап пробы, ждёт после запуска контейнера пока не начнёт исполняться лайвнесс проба
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30 # 30 проваленных проверок
          periodSeconds: 10 # с периодом 10 секунд
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
...
