---
apiVersion: apps/v1
kind: Deployment # тип ресурса в кубере, самое важное поле
metadata:
  name: deployment-to-persistent-nodes-appversion1 # имя деплоймента, именно к нему идёт привязка, если задеплоить, потом переименовать и задеплоить снова то и со старым именем будет деплой и с новым
spec:
  replicas: 2
  selector:
    matchLabels:      # задаём, что наш деплоймент рулит нодами, у которых эти лейбы
      instance: persistent
  strategy:
    rollingUpdate:
      maxSurge: 1   # количество подов, которое мы можем понять сверху(от числа replicas) при деплое на новую версию
      maxUnavailable: 1 # количество подов, которое мы можем убить(от числа replicas), при деплое
    type: RollingUpdate
  # =================== это шаблон, из которого мы создаём поды(создаём их уже в репликасете)
  template:
    metadata:
      labels:
        instance: persistent
        appversion: version1
    spec:
      containers:
      - image: adv4000/k8sphp:version1
        name: k8sphp
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volume-used-as-bind-to-node
          mountPath: /katalog-where-we-mount-in-container
      volumes:
      - name: volume-used-as-bind-to-node
        hostPath: # самое важное поле, оно рассказывает, что тип маунта - hostPath, что значит, что мы просто маунтим в контейнер каталог с ноды и всё
          path: /katalog-which-we-mount-on-node # на ноде он создаётся, если его не было ранее
